# Generated by Django 5.1.3 on 2024-11-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EA', '0004_book_title_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Enter a brief biography of the author', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='notable_achievements',
            field=models.TextField(blank=True, help_text='Significant achievements of the author', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='works',
            field=models.TextField(blank=True, help_text='List of works by the author', max_length=2000, null=True),
        ),
    ]
