# Generated by Django 5.1.3 on 2024-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EA', '0006_alter_book_category_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='EA.genre'),
        ),
    ]
