# Generated by Django 5.1.3 on 2024-12-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EA', '0007_alter_book_genre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
    ]
